### ISSUE TITLE
RPC 基本接口整理

### ISSUE THREAD

**Issue by fs7744** [TarsNET/rpc#1]

**Comment by fs7744** [comment]
基本接口整理如下图，已添加基本实现，不过各项细节没有完善

![image](https://user-images.githubusercontent.com/3265552/44632743-88407a80-a9b2-11e8-8d5f-e5abc382a246.png)

**Comment by fs7744** [comment]
done

**Comment by ElderJames** [comment]
Configuration和MSDI的依赖还需要移走

**Comment by fs7744** [comment]
Configuration 和 logging 会移到对应库中，只会留下对应Abstraction依赖

MSDI不必移除，DI实现各个框架千差万别，我们自己抽象实现各种适配会太累

像autofac 之类自己就对MSDI做了适配，

所以我们以MSDI作为自身处理标准，可以直接使用各项适配，不必自己搞一套
