### ISSUE TITLE
是否可以优化host的构建方式？

### ISSUE THREAD

**Issue by 893949088** [TarsNET/rpc#12]
我注意到tars的host的构建方式应该是参考了surging的host的构建方式，最初我在搭建grpc的api框架第一版的时候也是类似这种方式，但是后来发现这种方式随着功能也业务的扩展，会变得越来越臃肿，感觉现在的surging的host配置也有点这种感觉，不是很优雅。是否可以参照aspnetcore的startup类文件的方式去构建host? 我的第二版grpc框架是这样搞的，感觉相对好了一些。
github：https://github.com/893949088/Grpc-MicroService，大佬看看是否可有参考价值（还不是很完善，还有诸多问题）？

**Comment by ElderJames** [comment]
你的意思是利用builder去写扩展方法，而不是各种Addxxx吧，我们后面会讨论和改进。

**Comment by fs7744** [comment]
@ElderJames  @893949088 的意思应该是提供startup模板类处理，让di注入之类代码和 hostbuilder单独开

**Comment by 893949088** [comment]
@fs7744 是这个意思

**Comment by fs7744** [comment]
@893949088  非常感谢
后续我们会添加这样的方法
目前我们只是做了一些功能方面的整理，所以使用友好上面没有做多少思考
非常欢迎后续也提各种想法给我们

**Comment by fs7744** [comment]
暂时先用最简单的方式处理，后续有其他需求时再扩展

https://github.com/TarsNET/rpc/blob/develop/src/Tars.Net.Core/Hosting/StartupExtensions.cs
