### ISSUE TITLE
是否可以把mvc的model validate集成进去？或者提供可以这种扩展的口子？

### ISSUE THREAD

**Issue by 893949088** [TarsNET/rpc#14]

**Comment by fs7744** [comment]
可以用 aop 实现对应拦截器所有的做法和想法
这也是我们引入aop框架作为基础的目的

**Comment by fs7744** [comment]
AspectCore 的 datavalidation 示例 ：

https://github.com/dotnetcore/AspectCore-Framework/blob/master/datavalidation/sample/AspectCore.Extensions.DataAnnotations.Sample/Program.cs
