### ISSUE TITLE
Tars是否会有一个配置中心？

### ISSUE THREAD

**Issue by movingsam** [TarsNET/rpc#28]
研究了一段时间Tars的Rpc部分，发现Tars很依赖配置文件，本来写在特性中的ServantName也移到了config中是不是说Tars会有一个配置中心的存在来统一调整配置呢？

**Comment by ElderJames** [comment]
是的，对接Tars框架后，就能利用框架上的公共框架节点，其中就有Config（配置中心）
https://github.com/TarsCloud/Tars/blob/master/Introduction.md

**Comment by movingsam** [comment]
谢谢解答。
