### ISSUE TITLE
是否提供AOP编程？方便处理一些共通逻辑？

### ISSUE THREAD

**Issue by 893949088** [TarsNET/rpc#9]

**Comment by ElderJames** [comment]
刚好我们正在讨论 #8 
不过你可以具体介绍下您说的AOP编程是什么？
是需要提供类似Mvc里面的Filter，可以在请求前和请求后做处理么？

**Comment by 893949088** [comment]
差不多类似MVC里面的Filter（最好提供基于channel全局的和基于action的两种），最好可以精准的控制返回的结果，考虑这种rpc的出入参都是强类型的，是否可以搞什么client可以判断的某种status的什么之类的，或者提供什么异常类可以方便捕捉。
比如目前我这边使用的grpc搭建的api吧，grpc有提供interceptor这种东西，我在定义每个api的出参的时候都定义了固定格式：
`message AddUserReply{
	bool Success=1;
	string Code=2;
	string Message=3;
	message ReplyData{
               ******
               ******
	}
	ReplyData Data=4;
}`
在我业务代码里面如果遇到需要检查或者业务代码不通过的时候，我会throw 一个定义好的exception，然后再interceptor捕捉，然后把message赋值到出参的message并且success是false，然后再client的interceptor查看api返回的success是false或者接口不通的情况下，我还会再抛异常给client，逐层throw，最后再mvc api那里返回给前端脚本。
希望tars不只是api框架，再工程上做的更好一点

**Comment by fs7744** [comment]
@893949088 你所说的功能已经关联到 #10，在其完成后我们会添加对应demo示例说明， 后续你可以在 #10 追踪我们的进度

为了方便我们整理功能，当前issue我们会关闭

如有其他想法或建议可以新建issue或重开当前issue

**Comment by fs7744** [comment]
demo 示例：

https://github.com/TarsNET/examples/blob/master/CustomizedProtocol%20(json)%20and%20BusinessExceptionInterceptor/CustomizedProtocolCommon/BusinessExceptionInterceptorAttribute.cs
